# Generated by Django 5.1.6 on 2025-03-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, unique=True, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер столика')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('in_waiting', 'В ожидании'), ('ready', 'Готово'), ('paid', 'Оплачено')], default='in_waiting', max_length=10, verbose_name='Статус')),
                ('slug', models.SlugField(editable=False, max_length=4, unique=True, verbose_name='URL-имя')),
                ('items', models.ManyToManyField(blank=True, to='orders.item', verbose_name='Блюда')),
            ],
        ),
    ]
