# Generated by Django 5.1.6 on 2025-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_item_name_item_dish_name_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='orders.item', verbose_name='Список блюд'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
